---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: db
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
      author: intelliqit
  template:
    metadata:
      name: postgres-pod
      labels:
        app: db
        author: intelliqit
    spec:
      containers:
        - name: mydb
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: intelliqit
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_DB
              value: mydb
...




